// generated by bin/handle_sprite_sheets.sh
import Blessing from './Blessing.json'
import BlessingImg from './Blessing.png'
import Diabolos from './Diabolos.json'
import DiabolosImg from './Diabolos.png'
import Engage from './Engage.json'
import EngageImg from './Engage.png'
import Item from './Item.json'
import ItemImg from './Item.png'
import Item_2 from './Item_2.json'
import Item_2Img from './Item_2.png'
import Majestic from './Majestic.json'
import MajesticImg from './Majestic.png'
import Mjolnir_Common from './Mjolnir_Common.json'
import Mjolnir_CommonImg from './Mjolnir_Common.png'
import Resonate from './Resonate.json'
import ResonateImg from './Resonate.png'
import Savior from './Savior.json'
import SaviorImg from './Savior.png'
import Status from './Status.json'
import StatusImg from './Status.png'
import Summon from './Summon.json'
import SummonImg from './Summon.png'
import Summon_Category from './Summon_Category.json'
import Summon_CategoryImg from './Summon_Category.png'
import UnitEdit from './UnitEdit.json'
import UnitEditImg from './UnitEdit.png'
import UnitEdit_2 from './UnitEdit_2.json'
import UnitEdit_2Img from './UnitEdit_2.png'

export const SPRITE_SHEETS = {
  Blessing: { ...Blessing, img: BlessingImg },
  Diabolos: { ...Diabolos, img: DiabolosImg },
  Engage: { ...Engage, img: EngageImg },
  Item: { ...Item, img: ItemImg },
  Item_2: { ...Item_2, img: Item_2Img },
  Majestic: { ...Majestic, img: MajesticImg },
  Mjolnir_Common: { ...Mjolnir_Common, img: Mjolnir_CommonImg },
  Resonate: { ...Resonate, img: ResonateImg },
  Savior: { ...Savior, img: SaviorImg },
  Status: { ...Status, img: StatusImg },
  Summon: { ...Summon, img: SummonImg },
  Summon_Category: { ...Summon_Category, img: Summon_CategoryImg },
  UnitEdit: { ...UnitEdit, img: UnitEditImg },
  UnitEdit_2: { ...UnitEdit_2, img: UnitEdit_2Img },
}
